### ISSUE TITLE
Добавить диалоговое окно при открытии URL с неуказанным типом json

### ISSUE THREAD

**Issue by just-blackot** [TheEntropyShard/JsonViewer#1]
Предлагаю добавить диалоговое окно при открытии URL у которого не указан явный json в заголовках пакета и/или URL не заканчивается на .json
_Если выполнена хоть одна из двух зависимостей, то окно не вызывать_
Тело:
Кажется, по адресу %запрашиваемый юрл% мы получим не JSON файл.
Вы уверены, что хотите открыть этот адрес?
Кнопка 1:
_Да_ (можно синего цвета)
Кнопка 2:
_Нет_

**Comment by TheEntropyShard** [comment]
Fixed in [Release 0.4.2](https://github.com/TheEntropyShard/JsonViewer/releases/tag/v0.4.2)
